--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/NetherByte233/NetherScoreboard
build-by-default: true
branches:
- main
projects:
  NetherScoreboard:
    path: ""
    icon: Icon.jpg
    ...
